/************************************************************\
 **     Copyright (c) 2012-2023 Anlogic Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	E:/project/dds/al_ip/multiplier.v
 ** Date	:	2023 10 01
 ** TD version	:	5.6.71036
\************************************************************/

`timescale 1ns / 1ps

module multiplier ( p, a, b );

	output [39:0] p;

	input  [19:0] a;
	input  [19:0] b;



	EG_LOGIC_MULT #( .INPUT_WIDTH_A(20),
				.INPUT_WIDTH_B(20),
				.OUTPUT_WIDTH(40),
				.INPUTFORMAT("UNSIGNED"),
				.INPUTREGA("DISABLE"),
				.INPUTREGB("DISABLE"),
				.OUTPUTREG("DISABLE"),
				.IMPLEMENT("AUTO")
			)
			inst(
				.a(a),
				.b(b),
				.p(p),
				.cea(1'b0),
				.ceb(1'b0),
				.cepd(1'b0),
				.clk(1'b0),
				.rstan(1'b0),
				.rstbn(1'b0),
				.rstpdn(1'b0)
			);


endmodule