/************************************************************\
 **     Copyright (c) 2012-2023 Anlogic Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	E:/project/dds/al_ip/ROM_Atan.v
 ** Date	:	2023 10 02
 ** TD version	:	5.6.71036
\************************************************************/

`timescale 1ns / 1ps

module ROM_Atan ( doa, addra, clka );

	output [31:0] doa;

	input  [4:0] addra;
	input  clka;



	EG_LOGIC_BRAM #( .DATA_WIDTH_A(32),
				.ADDR_WIDTH_A(5),
				.DATA_DEPTH_A(32),
				.DATA_WIDTH_B(32),
				.ADDR_WIDTH_B(5),
				.DATA_DEPTH_B(32),
				.MODE("SP"),
				.REGMODE_A("NOREG"),
				.IMPLEMENT("9K"),
				.DEBUGGABLE("NO"),
				.PACKABLE("NO"),
				.INIT_FILE("../src/arctan/atan_expand16.mif"),
				.FILL_ALL("NONE"))
			inst(
				.dia({32{1'b0}}),
				.dib({32{1'b0}}),
				.addra(addra),
				.addrb({5{1'b0}}),
				.cea(1'b1),
				.ceb(1'b0),
				.ocea(1'b0),
				.oceb(1'b0),
				.clka(clka),
				.clkb(1'b0),
				.wea(1'b0),
				.web(1'b0),
				.bea(1'b0),
				.beb(1'b0),
				.rsta(1'b0),
				.rstb(1'b0),
				.doa(doa),
				.dob());


endmodule